### PR TITLE
Fix provisioning cms

### PR DESCRIPTION
**Pull request by lolepezy**
This is to fix strange validation errors fir provisioning CMSs. BouncyCastle tries to verify signingTime fields that are optional according to https://tools.ietf.org/html/rfc6492

### CODE REVIEW

**Comment by lolepezy** [comment]
@omuravskiy 
The actual change is in ProvisioningCmsObjectParser.java and it is 
....`build(cmsCertificate)) `to 
....`build(cmsCertificate.getPublicKey())`
Everything else is indeed cosmetics.

**Comment by omuravskiy** [comment]
OK

**Comment by wibisono** [comment]
[Signing-Time Attribute](https://tools.ietf.org/html/rfc6492#section-3.1.1.6.4.3) MAY be present, so it is optional. Also [Binary-Signing-Time Attribute](https://tools.ietf.org/html/rfc6492#section-3.1.1.6.4.3) MAY be present. 

But  `either one of the signing-time attribute or the binary-signing-time   attribute, or both attributes, MUST be present.` So individually they are optional, but one of them must be there.

This makes me wonder if we can verify the signature only using public key, because this implies we [ignore signing time](https://stackoverflow.com/questions/56614572/what-exactly-does-signer-verifysignerinformationverifier-verify).

**Comment by wibisono** [comment]
> This makes me wonder if we can verify the signature only using public key, because this implies we [ignore signing time](https://stackoverflow.com/questions/56614572/what-exactly-does-signer-verifysignerinformationverifier-verify).

Maybe we may validate using public key, because the [point 5](https://tools.ietf.org/html/rfc6492#section-3.1.3) in this check list of CMS validity only said that the signing time MAY lie within validity of EE certificate, so it is not a MUST.

Instead, what is required in this CMS object validation is that signing time should be greater or equal time value in previously valid CMS object passed from the same originator.

**Comment by omuravskiy** [comment]
> Maybe we may validate using public key, because the [point 5](https://tools.ietf.org/html/rfc6492#section-3.1.3) in this check list of CMS validity only said that the signing time MAY lie within validity of EE certificate, so it is not a MUST.
> 
> Instead, what is required in this CMS object validation is that signing time should be greater or equal time value in previously valid CMS object passed from the same originator.

RFC6488 (Signed Object Template for the Resource Public Key Infrastructure (RPKI)) explicitly says that 
>  the presence or
>   absence of the signing-time attribute MUST NOT affect the validity of
>   the signed object
(and the same for binary time).

**Comment by wibisono** [comment]
Indeed, RFC6488 is the correct basis for [RPKISignedObjectParser](https://github.com/RIPE-NCC/rpki-commons/pull/12/files#diff-fbc85b28821445b3accb908cd75cd5b8) which is already using public key to create verifier.

The second part of this pull request is about [ProvisioningCMSParser](https://github.com/RIPE-NCC/rpki-commons/pull/12/files#diff-9375fcc9c0f56c4ed945355ec5350b16) which should AFAIK should refers to RFC6492. We are now changing from creating verifier based on certificate (thus validating signing time) into public key, following RPKIObjectParser/RFC6488 that ignores it.

So still the question remains, for ProvisioningCMS.

**Comment by lolepezy** [comment]
It seems to be a correct or, at least, not damaging change.

**Pull request merged**
